language: python
services:
  - docker
install:
  - echo "Nothing to install"
env:
  global:
    - OPENSTUDIO_VERSION: 2.6.0
    - OPENSTUDIO_SHA: ac20db5eff
jobs:
  include:
    - stage: test and build
      sudo: required
      script:
        - docker build -t openstudio:latest --build-arg OPENSTUDIO_VERSION=$OPENSTUDIO_VERSION --build-arg OPENSTUDIO_SHA=$OPENSTUDIO_SHA .
        - docker run -it -v $(pwd):/var/simdata/openstudio openstudio:latest ruby /var/simdata/openstudio/test/test.rb
        - docker run -it openstudio:latest /usr/local/openstudio-$OPENSTUDIO_VERSION/Radiance/bin/rtrace -version
      after_success:
        - ./deploy_docker.sh
    - stage: test and build
      sudo: required
      script: ./singularity/deploy_singularity.sh
