sudo: required
language: python
services:
  - docker
install:
  - echo "Nothing to install"
script:
  - docker build -t openstudio:latest .
  - docker run -it openstudio:latest ruby /root/test.rb
after_success:
  - deploy_docker.sh
