sudo: required
language: python
services:
  - docker
install:
  - echo "Nothing to install"
script:
  - docker build -t openstudio:latest .
  - docker run -it -v $(pwd):/var/simdata/openstudio openstudio:latest ruby /var/simdata/openstudio/test/test.rb
  - docker run -it openstudio:latest /usr/local/openstudio-$(docker run -it openstudio:latest 'ruby -r openstudio -e "puts OpenStudio.openStudioLongVersion"')/Radiance/bin/rtrace -version
after_success:
  - ./deploy_docker.sh
